### ISSUE TITLE
Spotify credentials are public

### ISSUE THREAD

**Issue by Dark3clipse** [Psychotechnopath/spotify_project#1]
Don't put your Spotify client ID and client secret publicly in the repo, this is a security breach. ;)

You can do this as follows:
1) create a `.env` file:
```
CLIENT_ID=myid
CLIENT_SECRET=mysecret
```

2) load this in python:
```
from os.path import join, dirname
from dotenv import load_dotenv

# Create .env file path.
dotenv_path = join(dirname(__file__), '.env')

# Load file from the path.
load_dotenv(dotenv_path)
```
3) Add your `.env` file in a `.gitignore` file:
```
.env
```

**Comment by Psychotechnopath** [comment]
Whoopsie daisy. Thanks for the hotfix =).

**Comment by Psychotechnopath** [comment]
This presents an opportunity for learning; If you would have submitted this as pull request, I could have merged your code with my master branch to solve the issue right? And I could have linked this issue in my commit to solve it as well?

**Comment by Dark3clipse** [comment]
Yes it's meant as a learning opportunity, I don't have the time to create a pull request for you but it may be something to look out for in your next projects.
